from listas import LinkedList

l = LinkedList()
print(f"L esta vacia: {l.is_empty()}")
l.append(1)
l.append(2)
l.append(4)
l.append(5)
print(f"L esta vacia: {l.is_empty()}")
l.transversal()
#l.remove(10)
l.transversal()
#l.preppend(8)
l.transversal()

x = l.tail()
print(x.data)
print(l.get())
l.add_before(1,3)
l.transversal()
